/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo': RouteRecordInfo<
      '/demo',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/http-demo': RouteRecordInfo<
      '/http-demo',
      '/http-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/languages': RouteRecordInfo<
      '/languages',
      '/languages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/layouts': RouteRecordInfo<
      '/layouts',
      '/layouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use-request-demo': RouteRecordInfo<
      '/use-request-demo',
      '/use-request-demo',
      Record<never, never>,
      Record<never, never>,
      | '/use-request-demo/basic'
      | '/use-request-demo/effect'
      | '/use-request-demo/run'
    >,
    '/use-request-demo/basic': RouteRecordInfo<
      '/use-request-demo/basic',
      '/use-request-demo/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use-request-demo/effect': RouteRecordInfo<
      '/use-request-demo/effect',
      '/use-request-demo/effect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use-request-demo/run': RouteRecordInfo<
      '/use-request-demo/run',
      '/use-request-demo/run',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/demo.vue': {
      routes:
        | '/demo'
      views:
        | never
    }
    'src/pages/http-demo.vue': {
      routes:
        | '/http-demo'
      views:
        | never
    }
    'src/pages/languages.vue': {
      routes:
        | '/languages'
      views:
        | never
    }
    'src/pages/layouts.vue': {
      routes:
        | '/layouts'
      views:
        | never
    }
    'src/pages/use-request-demo.vue': {
      routes:
        | '/use-request-demo'
        | '/use-request-demo/basic'
        | '/use-request-demo/effect'
        | '/use-request-demo/run'
      views:
        | 'default'
    }
    'src/pages/use-request-demo/basic.vue': {
      routes:
        | '/use-request-demo/basic'
      views:
        | never
    }
    'src/pages/use-request-demo/effect.vue': {
      routes:
        | '/use-request-demo/effect'
      views:
        | never
    }
    'src/pages/use-request-demo/run.vue': {
      routes:
        | '/use-request-demo/run'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
