services:
  mysql:
    image: mysql:8.0
    container_name: mason-backend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mason-db}
      TZ: Asia/Shanghai
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mason_mysql_data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: mason-backend-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  mason_mysql_data:
