import { ERROR_TYPES } from '../config/constants'

export class AppError extends Error {
  constructor(message: string, public readonly bodyCode?: number, public readonly httpStatus = 200) {
    super(message)
  }
}

export const errorCodeMap: Record<string, number> = {
  [ERROR_TYPES.NAME_OR_PASSWORD_IS_REQUIRED]: 400,
  [ERROR_TYPES.USER_ALREADY_EXISTS]: 409,
  [ERROR_TYPES.USER_NOT_EXISTS]: 400,
  [ERROR_TYPES.PASSWORD_IS_INCORRECT]: 400,
  [ERROR_TYPES.UNAUTHORIZATION]: 401,
  [ERROR_TYPES.UNPERMISSION]: 401,
  [ERROR_TYPES.MENU_NOT_EXISTS]: 400,
  [ERROR_TYPES.MENU_ALREADY_EXISTS]: 409,
  [ERROR_TYPES.INITIAL_ADMIN_CANNOT_BE_DELETED]: 401,
  [ERROR_TYPES.INITIAL_ADMIN_CANNOT_BE_MODIFIED]: 401,
  [ERROR_TYPES.INITIAL_ROLE_CANNOT_BE_MODIFIED]: 401,
  [ERROR_TYPES.INITIAL_ROLE_CANNOT_BE_DELETED]: 401,
  [ERROR_TYPES.ROLE_ALREADY_EXISTS]: 409,
  [ERROR_TYPES.ROLE_NOT_EXISTS]: 400,
  [ERROR_TYPES.ROLE_HAS_ASSOCIATED_USERS]: 400,
  [ERROR_TYPES.CANNOT_DELETE_SELF]: 409,
  [ERROR_TYPES.DEPT_NOT_EXISTS]: 400,
  [ERROR_TYPES.DEPT_HAS_ASSOCIATED_USERS]: 400
}
