/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../components/ErrorMessage/403.vue')['default']
    404: typeof import('./../components/ErrorMessage/404.vue')['default']
    500: typeof import('./../components/ErrorMessage/500.vue')['default']
    Column: typeof import('./../components/Column/index.vue')['default']
    ColumnSetting: typeof import('./../components/CustomTable/column-setting.vue')['default']
    CustomTable: typeof import('./../components/CustomTable/index.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FullLoading: typeof import('./../components/Loading/full-loading.vue')['default']
    LineTree: typeof import('./../components/LineTree/index.vue')['default']
    List: typeof import('./../components/List/index.vue')['default']
    Lottie: typeof import('./../components/Lottie/index.vue')['default']
    MasonProFormMain: typeof import('./../components/Form/mason-pro-form-main.vue')['default']
    MasonProInput: typeof import('./../components/Form/mason-pro-input.vue')['default']
    MasonProInputNumber: typeof import('./../components/Form/mason-pro-input-number.vue')['default']
    MasonProRadio: typeof import('./../components/Form/mason-pro-radio.vue')['default']
    MasonProRate: typeof import('./../components/Form/mason-pro-rate.vue')['default']
    MasonProSelect: typeof import('./../components/Form/mason-pro-select.vue')['default']
    MasonProSlider: typeof import('./../components/Form/mason-pro-slider.vue')['default']
    MasonProSwitch: typeof import('./../components/Form/mason-pro-switch.vue')['default']
    MasonProTree: typeof import('./../components/Form/mason-pro-tree.vue')['default']
    Notification: typeof import('./../components/Notification/index.vue')['default']
    NotificationList: typeof import('./../components/Notification/notification-list.vue')['default']
    SearchFormFilter: typeof import('./../components/SearchFormFilter/index.vue')['default']
    SearchFormFilterItem: typeof import('./../components/SearchFormFilter/components/search-form-filter-item.vue')['default']
    StyleSetting: typeof import('./../components/CustomTable/style-setting.vue')['default']
    SvgRender: typeof import('./../components/SvgRender/index.vue')['default']
    Table: typeof import('./../components/Table/index.vue')['default']
    Watermark: typeof import('./../components/Watermark/index.vue')['default']
  }
}
